org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# Check these against https://fabricmc.net/develop for the version you target.
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.blueprintclient
archives_base_name=blueprint-client-mod

# Dependencies
fabric_version=0.141.6+1.21.11
